autoshop/accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$',
        auth.LoginView.as_view(template_name='accounts/login.html', success_url=reverse_lazy('index')),
        name='login'),
    url(r'^logout/$', auth.LogoutView.as_view(template_name='accounts/logged_out.html'), name='logout'),
    url(r'^signup/$', views.UserSignUpView.as_view(), name='signup'),
]

autoshop/autoshop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

autoshop/accounts/models.py
from django.db import models as db_models
from django.contrib.auth import models


# Create your models here.

class User(models.User, models.PermissionsMixin):
    USER_TYPE_CHOICES = (
        ('pr', 'PR'),
        ('mech', 'Mechanic'),
        ('client', 'Client'),
    )

    user_type = db_models.CharField(max_length=6, choices=USER_TYPE_CHOICES, default='client')

    def __str__(self):
        return self.username

autoshop/accounts/forms.py
from . import models
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'user_type')
        model = models.User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['email'].label = 'Email Address'
        self.fields['user_type'].label = 'I am:'

autoshop/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import models, forms


class UserSignUpView(CreateView):
    model = models.User
    form_class = forms.UserCreateForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('index')

autoshop/autoshop/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

autoshop/accounts/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block body %}
    <div class="jumbotron">
        <h2>Logged Out</h2>
    </div>
{% endblock %}

autoshop/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>

<nav class="navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    </div>
</nav>

<div class="container">
    <div class="jumbotron">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-default" value="Submit">
        </form>
    </div>
</div>
</body>
</html>

autoshop/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AutoShop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
<nav class="navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

autoshop/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>Welcome!</h1>
{% endblock %}